all: medusa_account_de.pdf medusa_account_en.pdf

medusa_account_de.pdf:
	pdflatex medusa_account_de.tex

medusa_account_en.pdf:
	pdflatex medusa_account_en.tex

clean:
	rm -rf *.aux *.log medusa_account*.pdf
